# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Number',
        ),
    ]
