# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170621_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
