# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170627_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
